#!/usr/bin/env bash
#installs and configures an nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "21s/^listen .*/listen 80/" /etc/nginx/sites-enabled/default
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/^\sserver_name.*/a\ rewrite ^/redirect_me https://www.google.com prmanent;" /etc/nginx/sites-available/default;
sudo service nginx start
