#!/usr/bin/env bash
#create a mysql dump and compress the file. Backs up db

pwd="$1"
archive_name=$(date +'%d-%m-%Y')

mysqldump -u root --password="$pwd" --all-databases > backup.sql

mkdir archive

mv backup.sql archive/

tar -czf "${archive_name}.tar.gz" archive

rm -r archive
