#!/usr/bin/env bash
#installs and starts an nginx server

# suppress any interactive prompts during installation
export DEBIAN_FRONTEND=noninteractive

sudo apt-get update
sudo apt-get install -y curl
sudo apt-get install -y nginx
sudo service nginx start

