#!/usr/bin/env bash
#installs and starts an nginx server

# suppress any interactive prompts during installation
export DEBIAN_FRONTEND=noninteractive

apt-get update -y
apt-get install -y curl
apt-get install -y nginx
/usr/sbin/nginx
curl 0:80
