#!/usr/bin/env bash
#print phrase n times using until loop. In 9th iteration print phrase then hi
#on new line

phrase="Best School"
otherPhrase="Hi"
start=1

while [ $start -le 10 ]
do
    if [ $start -eq 9 ]
    then
        printf "%s" "$phrase"
        echo " "
        echo "$otherPhrase"
    else
        echo "$phrase"
    fi
    
    start=$((start + 1))
done
    
