#!/usr/bin/env bash


totalHours=12
totalMins=59
i=0

while [ $i -le $totalHours ]
do
    echo "Hour: $i"
    j=1
    while [ $j -le $totalMins ]
    do
        echo "$j"
        j=$((j + 1))
    done
    i=$((i + 1))
done
