#!/usr/bin/env bash
#checks if a file exists

file="school"

if test -e $file
then
    echo "$file file exists"
    if test -s $file
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi

    if test -r $file
    then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi

